Hexcasting.Actions["hexal:current_tick"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:breath"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:health"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:armour"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:toughness"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:light_level"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:factorial"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:running/sum"] = function(self, castEnv)
    local inputList = castEnv.stack:pop().list --TODO: use the iota math ops
    local outputList = Hexcasting.Iotas["hexcasting:list"]:new()
    local sum = inputList[1]:copy():multiply(Hexcasting.Iotas["hexcasting:double"]:new(0))
    for _,number in pairs(inputList) do
        local newnum = number:add(sum)
        outputList:append(newnum:copy())
        sum = sum:add(number)
    end
    castEnv.stack:push(outputList)
end
Hexcasting.Actions["hexal:running/mul"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:everbook/read"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:everbook/write"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:everbook/delete"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:everbook/toggle_macro"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:smelt"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:freeze"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:falling_block"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:place_type"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:particles"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/summon/projectile"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/summon/ticking"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/self"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/media"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/hex"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/owner"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/move/target/set"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/move/target/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/move/speed/set"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/move/speed/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/transfer/allow"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/transfer/disallow"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/transfer/others/allow"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/transfer/others/disallow"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:get_entity/wisp"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:zone_entity/wisp"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:zone_entity/not_wisp"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/trigger/tick"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/trigger/comm"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/trigger/move"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/seon/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/others"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/unlink"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/unlink/others"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/get_index"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/num"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/comm/send"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/comm/read"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/comm/num"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/comm/clear"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/comm/open_transmit"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:link/comm/close_transmit"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:gate/mark"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:gate/unmark"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:gate/mark/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:gate/close"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/storage/bind"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/storage/bind/temp"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/contained_type/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/contained/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/storage/remaining_capacity/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/storage/contains"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/make"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/return"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/combinable"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/split"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/storage/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/storage/set"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/craft"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/craft/preview"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/villager/level/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/trade/get"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/trade"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:mote/use_on"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/consume"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:wisp/seon/set"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:tick"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:gate/make"] = function(self, castEnv) Unimplemented(self) end
Hexcasting.Actions["hexal:interop/fabric_only/phase_block"] = function(self, castEnv) Unimplemented(self) end